### ISSUE TITLE
archProfilAAR -> rename

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/recexcavAAR#1]
Rename the branch to profileAAR

**Comment by MoritzMennenga** [comment]
@nevrome is there an easy way to rename all the things to profileAAR?

**Comment by nevrome** [comment]
What do you mean by "all the things"? The name of the package should not be changed now because it's already on CRAN. We could outsource the code into an own package - but why? The name of the branch is completely irrelevant because it will be merged into the master anyway.

**Comment by MoritzMennenga** [comment]
I mean renaming archprofile function in profilAAR without getting shot by Travis.

**Comment by nevrome** [comment]
Ah - ok. The -AAR-thing is reserved for packages, not individual functions. The function name should fit in with the other functions in recexcavAAR. You can take a look at the NAMESPACE file to get an idea, how the other functions are named. Mostly combinations of abbreviations without snake or camelcase.

**Comment by MoritzMennenga** [comment]
Ok, I thought about it, because later the Python Plugin should have a AAR name, and thought therefore it would be nice, if all the same functions/plugin stuff has the same name

**Comment by nevrome** [comment]
We never discussed about naming conventions for python plugins. The -AAR suffix initially meant **A**nalysis in **AR**chaeology - so it's not directly related to R. Nevertheless I would prefer to have another naming scheme for the python stuff. 

Let's talk about this in the next ISAAK meeting. Everbody loves name discussions.

**Comment by MoritzMennenga** [comment]
Ok, we can discuss it. I thought, AAR is the official ISAAK brand, part of the coporate identity ;-)
