### ISSUE TITLE
profilAAR -> Tests

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/recexcavAAR#2]
As @nevrome mentioned, maybe the best way is to build tests at first, then checking an optimizing the code.

**Comment by nevrome** [comment]
I created a [very simple and limited continuity test](https://github.com/ISAAKiel/recexcavAAR/blob/archProfile/tests/testthat/test_archprofile.R). For sure you could (and should) add some more comprehensive tests, @MoritzMennenga. See [here](http://r-pkgs.had.co.nz/tests.html) for an introduction if you're not familiar with testthat.

**Comment by MoritzMennenga** [comment]
I added new testdata and two tests. 
One for the standart values direction = horizontal and view = projected
and one for direction = original and view = surface
