### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by MoritzMennenga** [ISAAKiel/recexcavAAR#7]
Write a publication (CAA journal?).

**Comment by MoritzMennenga** [comment]
Journal of Field Archaeology -> Embargo 18 Month or 2150€
Journal of Computer Applications in Archeology -> OA £300 per article

**Comment by MartinHinz** [comment]
With first author at Kiel University who's Master Thesis is not longer than 10 years ago: up to 2000 € funding for Open Access Publication. But have to be a pure OA journal. See [instructions](https://www.ub.uni-kiel.de/news/Publfonds.pdf)
