### ISSUE TITLE
feature requests for archprofile()

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/recexcavAAR#8]
Would be nice to have...

**1.** A version of `archprofile()` which deals with only one profile. Maybe the more complex version which works with many profiles could call the basic one. Something comparable to our solution for the grouping in [mortAAR](https://github.com/ISAAKiel/mortAAR/blob/master/R/analytical_functions.R). 

**2.** A version that doesn't need the a SpatialPointsDataFrame input. I can't see why we need this complicated data structure here except for the GIS interaction. Am I missing something? The SpatialPointsDataFrame version could be another wrapper for the two functions mentioned in **1.**.

**Comment by MoritzMennenga** [comment]
I think using dataframe is easy, because the spatialdataframe will be converted in the beginning of the code. we can make it optional. The possibility for using the sdf is important I think, because normally spatial data is in a sdf, the information of the reference system aso. will be saved if you use a sdf.
Making a version for using only one profile is simple, we have to remove the loops. But I don't see  
advantage. If we do so, we have two times nearly the exact identical code, don't we?

**Comment by nevrome** [comment]
We can avoid identical code if the function for multiple profiles simply calls the one for one profile.

**Comment by MoritzMennenga** [comment]
Ok, I understand, but I don't get why to do this

**Comment by nevrome** [comment]
To use `archprofile()` also for just one profile right now requires a (SpatialPoints)DataFrame with the profile_col and view_col columns. We could reduce this to something like this:

```
archprofile_one_profile <- function(dataframe_with_only_x_y_z, view_dir = "N", view = "projected",  direction = "horizontal")
```

or

```
archprofile_one_profile <- function(vector_x, vector_y, vector_z, view_dir = "N", view = "projected",  direction = "horizontal")
```

That should also be enough. And it's much more simple if you really just want to rectify one image. Also debugging for us is more easy, because you don't need the big loop in the one-profile-function.

**Comment by MoritzMennenga** [comment]
I don't know if it is a good idea, in perspective to the python plugin. I don't know how this python stuff works, but if we have to redo it for the plugin, it is not worth the work. 
By the way, we can do a one profile solution if you like, but from my point of view it is makeing everything more complicated and it is not needed.
There are no bugs :-D

**Comment by MoritzMennenga** [comment]
It is possible to use SpatialDataFrames and DataFrames now
```

#' @param fotogram_pts SpatialPointsDataFrame. A sp::SpatialPointsDataFrame or dataframe containing the control points (3 Dimensions).

#' @param profile_col character. Name of the column containing the profile group variable (profile number).

#' @param view_col character. Name of the profile containing the viewing direction ("N","S","W","E").

#' @param view character. Direction of view on the Profile.

#' @param x character. (optional) If input is a dataframe, column with x coordinates.

#' @param y character. (optional) If input is a dataframe, column with y coordinates.

#' @param z character. (optional) If input is a dataframe, column with z coordinates.

```

**Comment by MoritzMennenga** [comment]
I added a one profile function
there are some doublications of variables because it is a derivate of the original function.
